version: "3.8"

services:
  app:
    build: .
    container_name: chatbot_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: Saw50812@
      DB_DATABASE: lc_bot
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: sql_chatbot
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Saw50812@
      MYSQL_DATABASE: lc_bot
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
